services:
  api:
    build:
      context: .
      dockerfile: ApiDockerExample/Dockerfile
    container_name: apidockerexample
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserverdb;Database=ApiDockerDB;User Id=sa;Password=ku.dev@2305;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ku.dev@2305
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
