[build]
builder = "dockerfile"
dockerfilePath = "ApiDockerExample/Dockerfile"

[deploy]
startCommand = "dotnet ApiDockerExample.dll"
restartPolicyType = "always"
healthcheckPath = "/health"
sleep = false